### ISSUE TITLE
The url "/content/wikipedia_en_all" was not found on this server

### ISSUE THREAD

**Issue by imclerran** [offspot/overview#4]
I downloaded and flashed an image from the online custom image creation tool within the last week. After connecting to the hotspot, each of the requested zim files show up on the kiwix landing page, however, when I attempt to access *any* of them, the server returns a url not found error.

**Comment by rgaudin** [comment]
@Popolechien, this mandates communication to users who created cards between Saturday February 17th @ 18:50 UTC and Wednesday February 21st @ 12:53 UTC.

That's 10 images, 7 people. Example wording:

> Dear Imager Service user,
>
> Between Saturday 2024-02-17 18:50 UTC and Wednesday 2024-02-21 18:50 UTC; all images created included a serious bug that breaks links to your ZIM content in the Hotspot dashboard (main page).
>
> Given you created an image during that period, we strongly advise you re-create it.
