### ISSUE TITLE
Update Categories List

### ISSUE THREAD

**Issue by rgaudin** [offspot/overview#5]
As discussed during Hackathon, we acknowledge that the current list of Categories (source-website based) is not satisfactory.

We want to replace it with a new –limited– list, based on _Knowledge families_ ; inspired by the Dewey Classification of the root categories of The Library of Congress or others. @Popolechien will submit something.

We also want those categories to be translated which will lead to a libkiwix ticket.
We also want to explore iconography for categories but this discussion will happen once we have settled on the new list.

**Comment by kelson42** [comment]
_Disclaimer: This is an ongoing draft_

* Literature (Romans, books, essays, ...)
* Conferences
* News (Kind of "journalism" work)
* Courses
* Knowledge References (Encyclopedia, dictionnary, scientific publication, ...)
* Popular culture (Fan work)
* Kids (dedicated to kids <12)
* Know-how Tutorial & guides (howtos of any sort, technical docs)
* Vulgarisation (explaining anything in a simple manner outside proper school/curriculum)
* Other

**Comment by Popolechien** [comment]
I was going to suggest working off [Dewey classes](https://en.wikipedia.org/wiki/List_of_Dewey_Decimal_classes) or the [Library of Congress Classification](https://en.wikipedia.org/wiki/Library_of_Congress_Classification), but considering the type of content we have this might work better.

**Comment by rgaudin** [comment]
Copied to https://github.com/kiwix/overview/issues/104
