### ISSUE TITLE
We need a Kiwix Hotspot logo

### ISSUE THREAD

**Issue by kelson42** [offspot/overview#7]
Kiwix Hotspot needs a proper logo. I have seen one with the Kiwix logo ball replaced by the WiFi signed, this would be fine to me.

**Comment by rgaudin** [comment]
Here are the Branding files we are currently using

## `horizontal-logo-light.png`
[![horizontal-logo-light](https://github.com/offspot/offspot-config/blob/main/src/offspot_config/branding/horizontal-logo-light.png?raw=true)](https://github.com/offspot/offspot-config/blob/main/src/offspot_config/branding/horizontal-logo-light.png)

## `square-logo-light.png`

[![square-logo-light](https://github.com/offspot/offspot-config/blob/main/src/offspot_config/branding/square-logo-light.png?raw=true)](https://github.com/offspot/offspot-config/blob/main/src/offspot_config/branding/square-logo-light.png)

**Comment by Popolechien** [comment]
I think we're  good with a single, unified logo. There can be unified variants but IMHO the question is more related to OpenZIM where we have a carrot for the zimfarm, an egg for zimit, and a green wordmark for the project.

**Comment by kelson42** [comment]
OK, so:
* logo: Kiwix logo
* name: Kiwix Hotspot

**Comment by kelson42** [comment]
@siemsie Can we have please a bitmap banner with logo and "Kiwix Hotspot" to replace current one? 

![Image](https://github.com/offspot/overview/assets/1029718/3eabf294-2d35-4430-947d-ead714656e7a)

**Comment by siemsie** [comment]
![Kiwix-Hotspot-logo-insitu](https://github.com/offspot/overview/assets/61543885/80c0fbd6-93ec-47b9-b6dc-ba61bc57b5e1)
![Kiwix-Hotspot-logo](https://github.com/offspot/overview/assets/61543885/109acc65-27ed-4ca1-a44b-f795f950266d)
![Kiwix-Hotspot-logo](https://github.com/offspot/overview/assets/61543885/5107e533-a2fd-4de1-a07e-4fcaef3525fd)
Hi all. In the hope that I have understood your request, here are png, svg, and insitu files... Is it what you had in mind?

**Comment by Popolechien** [comment]
Sans serif please.

**Comment by rgaudin** [comment]
> Sans serif please.

There's no serif option ; it's GH rendering the SVG that looks like a serif text

**Comment by Popolechien** [comment]
Ah TIL.

**Comment by kelson42** [comment]
There is a problem here, these logo are not dark mode friendly, here is for example how it looks like to me:
![image](https://github.com/offspot/overview/assets/1029718/1c72fdfc-400e-44cc-89aa-40875492baa1)

Considering that the support of Dark mode is a most for our solution, we need a solution to that problem,

**Comment by Popolechien** [comment]
Not sure dark mode is priority, but ok.

**Comment by rgaudin** [comment]
You closely at the filename: `horizontal-logo-light.png` This logo is the light version because we decided to only support light mode in this iteration of the dashboard (because supporting both is obviously more work).
The only light/dark mode support we have is for the favicon.

**Comment by siemsie** [comment]
I can easily make a white version of the logo if needed – would that help or does it need to be a "one logo fits all"?

**Comment by kelson42** [comment]
After our discussion in Lausanne, we decided to have at the source an SVG with a dark-mode, so we the SVG files (both squared and long) with the proper dark and light CSS

**Comment by rgaudin** [comment]
I'll test inverting the color and send here the result so we can decide whether it is enough/acceptable or not

**Comment by rgaudin** [comment]
@siemsie can you make a version with the text flatten? This will ensure we never encounter rendering issues of the text

**Comment by siemsie** [comment]
![Kiwix-Hotspot-logo-outlined](https://github.com/user-attachments/assets/ac8fa363-54e6-4b26-ac0e-7a048ebabd2c)
Hi all. Is this what you require? I'm not sure I understood the request :/

**Comment by rgaudin** [comment]
Thank you @siemsie ; it's exactly what we wanted.

https://github.com/user-attachments/assets/5e8c12ad-b6ff-4fd2-bfd4-f70d98fde4d3

Could you please create a version where the artboard is a clean ratio? We had a 5.5 ratio for the previous, PNG version. This one is 1722x313 and thus 5.5015974441…

**Comment by rgaudin** [comment]
I've added the new logos with the theme and format variants: https://github.com/offspot/offspot-config/tree/main/src/offspot_config/branding

**Comment by kelson42** [comment]
I reopen as we need to store all of this properly so we can find it easily. I will do it.

**Comment by kelson42** [comment]
Finally, I have:
* Created https://github.com/offspot/overview/wiki/Visuals as Reference page for visuals
* https://github.com/offspot/.github/blob/main/profile/README.md which displayed as GitHub org banner

**Comment by rgaudin** [comment]
Nice!
