### ISSUE TITLE
Manage publishing of apps

### ISSUE THREAD

**Issue by Popolechien** [offspot/overview#8]
Following up on recent discussions, we need to have an option on the installer that would allow for the storage of APKs on the image that could later be downloaded by hotspot users. We currently have Africatik, Maths Matthews, etc. but in the short to medium-term we may have more to offer from Orange or other partners (or simply want to offer OsmAnd).

In terms of UX at installation I do not think it is important to distinguish whether a specific piece of content is dynamic or static as is the case currently. It would be more relevant to select a language, and have the app appear alphabetically with the zim files and an appropriate descriptor or tag.

Once connected to the Kiwix-server I also think that rather than clicking on a box and be taken to a download page, one could directly click on the box and start the download.

**Comment by rgaudin** [comment]
Closing as the main issue (mgmt of publishing of apps) has been implemented in IS. It's even called _Apps_!
The rest of the comments are improvements for the dashboard and should lead to issues there if there is still interest…
